app:
    build: app
    volumes:
        - app:/usr/src/app
        - data/logs/app:/usr/src/app/logs
    ports:
        - "8000:8000"
    links:
        - db
        - redis
        - amqp
    environment:
        DATABASE_URL: postgres://postgres@db/postgres
        REDIS_URL: redis://redis/1
        BROKER_URL: amqp://guest:guest@amqp/
db:
    image: postgres
    expose:
        - "5432"
web:
    build: web
    ports:
        - "80:80"
    links:
        - app
redis:
    image: redis
    expose:
        - "6379"
amqp:
    image: rabbitmq:management
    expose:
        - "5672"
        - "15672"
flower:
    image: nicholsn/docker-flower
    links:
        - amqp:mq
    ports:
        - "5555:5555"
