app:
    build: app
    volumes:
        - app:/usr/src/app
    ports:
        - "8000:8000"
    links:
        - db
    environment:
        DATABASE_URL: postgres://postgres@db/postgres
db:
    image: postgres
    expose:
        - "5432"
web:
    build: web
    ports:
        - "80:80"
    links:
        - app
