app:
    build: app
    volumes:
        - app:/usr/src/app
    ports:
        - "8000:8000"
    links:
        - db
        - redis
    environment:
        DATABASE_URL: postgres://postgres@db/postgres
        REDIS_URL: redis://redis/1
db:
    image: postgres
    expose:
        - "5432"
web:
    build: web
    ports:
        - "80:80"
    links:
        - app
redis:
    image: redis
    expose:
        - "6379"

